import { useEffect,useState } from 'react';
import { Bell, CheckCheck } from 'lucide-react';
import PageHeader from '../../components/layout/PageHeader';
import SectionCard from '../../components/common/SectionCard';
import Button from '../../components/common/Button';
import {Alert,EmptyBlock,LoadingBlock} from '../../components/common/Feedback';
import StatusBadge from '../../components/common/StatusBadge';
import {notificationService} from '../../services/dataService';
const Notifications=()=>{const[d,setD]=useState({items:[],unreadCount:0});const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=async()=>{try{setLoading(true);setD(await notificationService.list())}catch(e){setError(e.response?.data?.message||'Unable to load notifications.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);const read=async id=>{try{await notificationService.read(id);await load()}catch(e){setError(e.response?.data?.message||'Unable to update notification.')}};const readAll=async()=>{try{await notificationService.readAll();await load()}catch(e){setError(e.response?.data?.message||'Unable to update notifications.')}};if(loading)return <LoadingBlock text="Loading notifications..."/>;return <div className="animate-fade-in"><PageHeader title="Notifications" description="Stay informed about request assignments, maintenance progress, warranty alerts and system events." icon={Bell} action={<Button variant="outline" icon={CheckCheck} onClick={readAll} disabled={!d.unreadCount}>Mark all read</Button>}/>{error&&<div className="mb-4"><Alert>{error}</Alert></div>}{!d.items.length?<EmptyBlock title="No notifications" text="You're all caught up."/>:<div className="space-y-3">{d.items.map(n=><SectionCard key={n._id||n.notificationId} className={n.isRead?'':'border-blue-200 bg-blue-50/20'}><div className="flex gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${n.isRead?'bg-slate-100 text-slate-400':'bg-blue-100 text-blue-600'}`}><Bell size={17}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-xs font-bold text-[#09284d]">{n.title}</h3>{!n.isRead&&<StatusBadge status="ASSIGNED"/>}</div><p className="mt-1 text-xs leading-5 text-slate-600">{n.message}</p><p className="mt-2 text-[9px] text-slate-400">{n.createdAt?new Date(n.createdAt).toLocaleString('en-IN'):'—'}</p></div>{!n.isRead&&<button onClick={()=>read(n._id||n.notificationId)} className="self-start text-[9px] font-bold text-blue-600 hover:underline">Mark read</button>}</div></SectionCard>)}</div>}</div>};export default Notifications;
