const ROLES = {
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
  TECHNICIAN: 'TECHNICIAN',
};

const AVAILABILITY_STATUS = {
  AVAILABLE: 'AVAILABLE',
  BUSY: 'BUSY',
  OFFLINE: 'OFFLINE',
};

const ACCOUNT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

const ASSET_STATUS = {
  AVAILABLE: 'AVAILABLE',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  OUT_OF_SERVICE: 'OUT_OF_SERVICE',
  RETIRED: 'RETIRED',
};

const ASSET_CONDITION = {
  EXCELLENT: 'EXCELLENT',
  GOOD: 'GOOD',
  FAIR: 'FAIR',
  POOR: 'POOR',
  CRITICAL: 'CRITICAL',
};

const CRITICALITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const MAINTENANCE_STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
};

const PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const MAINTENANCE_TYPE = {
  PREVENTIVE: 'PREVENTIVE',
  CORRECTIVE: 'CORRECTIVE',
  EMERGENCY: 'EMERGENCY',
};

const NOTIFICATION_TYPE = {
  REQUEST_CREATED: 'REQUEST_CREATED',
  REQUEST_ASSIGNED: 'REQUEST_ASSIGNED',
  MAINTENANCE_STARTED: 'MAINTENANCE_STARTED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
  WARRANTY_EXPIRING: 'WARRANTY_EXPIRING',
  MAINTENANCE_OVERDUE: 'MAINTENANCE_OVERDUE',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
};

module.exports = {
  ROLES,
  AVAILABILITY_STATUS,
  ACCOUNT_STATUS,
  ASSET_STATUS,
  ASSET_CONDITION,
  CRITICALITY,
  MAINTENANCE_STATUS,
  PRIORITY,
  MAINTENANCE_TYPE,
  NOTIFICATION_TYPE,
};
